### PR TITLE
Remove const_missing method in favor of const_set

### PR DESCRIPTION
**Pull request by dmoss18**

### CODE REVIEW

**Comment by dblock** [comment]
Interesting. Could you provide a longer explanation please? 

This changes behavior and API. Needs tests, CHANGELOG, UPGRADING, a fixed build, etc.

**Comment by dmoss18** [comment]
Longer explanation is method_missing can hijack constants at a higher level. For example:

```ruby
class MyEnum
  include Ruby::Enum
  define MY_GOOD_CONST, 'good'
end

MY_HIJACKED_CONST = 'hijacked'.freeze
```
```sh
$> MyEnum::MY_GOOD_CONST // good
$> MyEnum::MY_HIJACKED_CONST // hijacked <-- this is bad
```

Now it appears that my enum contains the const that is defined outside the `MyEnum` class. This is unexpected and erroneous behavior.

Also, using `const_set` will raise a `NameError` instead of the custom error you defined, which is more ideal.

Tests and changelog to follow

**Comment by dblock** [comment]
How interesting, thanks!

**Comment by dmoss18** [comment]
The real risk is having one of your enums get re-defined somewhere else: 

```ruby
class MyEnum
  include Ruby::Enum
  define MY_GOOD_CONST, 'good'
end

MY_GOOD_CONST = 'bad'.freeze
```

```sh
$> MyEnum::MY_GOOD_CONST //bad
```

**Comment by dblock** [comment]
@dmoss18 Can you see ^^^ please, would like to get this merged.

**Comment by dblock** [comment]
Bump @dmoss18

**Comment by laertispappas** [comment]
@dmoss18 Are you about to fix this PR? I'm about to implement this if it's OK from you.

**Comment by dblock** [comment]
@laertispappas you should finish it, haven't heard from @dmoss18 for a while

**Comment by laertispappas** [comment]
I'm gonna close this one since it's being addressed in #16

**Pull request closed without merging**
